server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
  connection-timeout: 180000
spring:
  datasource:
    url: jdbc:mysql://${jdbchost:127.0.0.1}:3306/jk?useUnicode=true&characterEncoding=utf-8
    username: root
    password: JK@666bj=888
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 1024
      max-request-size: 1024
img:
  location: /root/lucky/imgservice/apache-tomcat-8.5.31/webapps/ROOT/
  serverpath: http://123.56.196.195:8082/



